INSERT INTO SPACE_SHIPS (name, movie) VALUES ('USS Enterprise', 'Star Trek');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Millennium Falcon', 'Star Wars');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Nostromo', 'Alien');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Discovery One', '2001: A Space Odyssey');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Serenity', 'Firefly/Serenity');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Galactica', 'Battlestar Galactica');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Endurance', 'Interstellar');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Event Horizon', 'Event Horizon');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Eagle 5', 'Spaceballs');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Protector', 'Galaxy Quest');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Heart of Gold', 'The Hitchhiker''s Guide to the Galaxy');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Razor Crest', 'The Mandalorian');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Bebop', 'Cowboy Bebop');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Axiom', 'WALL-E');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Icarus II', 'Sunshine');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Valley Forge', 'Silent Running');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Covenant', 'Alien: Covenant');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Hermes', 'The Martian');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Sulaco', 'Aliens');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Jupiter 2', 'Lost in Space');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Andromeda Ascendant', 'Andromeda');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Executor', 'Star Wars');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Daedalus', 'Stargate: Atlantis');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Orion III', '2001: A Space Odyssey');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Rocinante', 'The Expanse');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Red Dwarf', 'Red Dwarf');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Minbari Cruiser', 'Babylon 5');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Elysium', 'Elysium');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('USS Kelvin', 'Star Trek');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('NSEA Protector', 'Galaxy Quest');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Prometheus', 'Prometheus');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Lexx', 'Lexx');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Heart of Gold', 'The Hitchhiker''s Guide to the Galaxy');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Venture Star', 'Avatar');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('NSEA Avenger', 'Galaxy Quest');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('USS Excelsior', 'Star Trek');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Executor', 'Star Wars');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('USS Voyager', 'Star Trek: Voyager');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Gunstar One', 'The Last Starfighter');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Dreadnought', 'Stargate SG-1');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Nebuchadnezzar', 'The Matrix');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('USS Defiant', 'Star Trek: Deep Space Nine');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Lewis & Clark', 'Event Horizon');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Yamato', 'Space Battleship Yamato');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('SS Botany Bay', 'Star Trek');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Hunter-Gratzner', 'Pitch Black');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Excalibur', 'Crusade');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('USS Franklin', 'Star Trek Beyond');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Tiger Claw', 'Wing Commander');
INSERT INTO SPACE_SHIPS (name, movie) VALUES ('Ghost', 'Interstellar');
